#!/bin/sh
Description=$1;
Username=$USER;
if [[ -z "$Description" ]]; then
  Description="`date +%Y-%m-%d" "%H:%M:%S` by ${Username^}";
fi
chmod -Rf 0755 .
chown -R webmaster:nginx ./
git add . && git commit -a -m "$Description";
git push --force -v origin main;
